### ISSUE TITLE
Better handling of large repositories when used as a git gem.

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#1]
Using git for large gems is slow to clone and uses a lot of disk space. Moved from https://github.com/bundler/bundler/issues/228

Approaches discussed include:

* Using a shallow clone (`--depth 1`). Doesn't work for fetching specific refs, which happens when loading from a `Gemfile.lock`, even if you don't specify the `ref` option in your `Gemfile`.
* Solving the problem elsewhere (such as by excluding the git directory when compiling a slug for heroku).

**Comment by quentindemetz** [comment]
Is it possible to specify a tarball in the Gemfile? Wouldn't that be a good solution that fixes the --depth conversations as well (at least for Github users) ?

**Comment by indirect** [comment]
Yes, it is possible to specify a tarball. Gems are tarballs, and the best way to use Bundler is to release gems and use them. :)

**Comment by nleo** [comment]
It's awful!

I add `gem 'spree', github: 'spree/spree'` and need wait 5+ minutes to install it!

Any progress?

**Comment by indirect** [comment]
The best way to avoid the problems of git gems is to build a gem from the repo and use that gem. Git repos are not a good match for single versions of gems.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4556
