### ISSUE TITLE
Support "bundle config mirror.<URL>" for :git sources

### ISSUE THREAD

**Issue by md5** [bundler/bundler-features#100]
Right now, the `bundle config mirror.<URL>` functionality only applies to `source`. It would be great if it applied to `gem` declarations with the `:git` attribute as well.

It's currently possible to work around this limitation using the "Local Git" feature and a user-maintained clone of a mirror repository, but it would be nice to be able to do something like this:

```console
$ bundle config mirror.'git@github.example.com:our-org/repo.git' \
  https://github.com/vendor/some-private-repo.git
```

I discussed the rationale for this feature in #98, but I think it's pretty self-explanatory. As I stated there, it seems like implementing this in `GitProxy#configured_uri_for` method by calling `Bundler.settings.mirror_for` would make sense. Since `mirror_for` uses `URI#parse`, there would have to be some code added to handle the fact that SCP-style `git@github.example.com:our-org/repo.git` remotes are not valid URIs.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4513

**Comment by ankitkataria** [comment]
@segiddins is this feature still required? :thinking: can I start working on it?
