### ISSUE TITLE
Support for npm packages

### ISSUE THREAD

**Issue by mockdeep** [bundler/bundler-features#101]
This is probably way out in left field, but I've been [struggling with npm packages](https://github.com/JedWatson/react-select/issues/606#issuecomment-159079865) recently and it seems like they've basically [punted on dependency resolution](https://docs.npmjs.com/misc/faq#why-can-t-npm-just-put-everything-in-one-place-like-other-package-managers) and they suggest that you start your own package manager if you don't like it. I was thinking it would be great if we could bring bundler's dependency resolution to node packages and that sort of got me off on a kick. It would be amazing if I could specify node dependencies in my `Gemfile` something like:

```ruby
ruby '2.1.7'
gem 'rspec'
node 'react'
```

Another alternative would be if bundler could read the `package.json` or something. I suspect it would be considered far out of scope for bundler, but thought I'd throw it out there.

**Comment by indirect** [comment]
Yeah, I think it's safe to say this is out of scope for Bundler, which only gets 5-10 hours per week of paid developer work. NPM, Inc. has raised over 10 million dollars and (iirc) hired more than ten full-time developers, so hopefully they can solve their own problems. :)

**Comment by krainboltgreene** [comment]
FWIW @mockdeep, if you created `bundler-node` I would test it out at work.

**Comment by mockdeep** [comment]
@krainboltgreene Thanks! I'll keep that in mind, but I wouldn't hold my breath. Already up to my neck with projects I should be doing a better job of maintaining. Hoping to get our team in a place where we can do a little more contribution, though.

Even at 5-10 hours per week, @indirect & co are doing a great job of providing a robust and easy to use tool.
