### ISSUE TITLE
Installation directory can be specified for each Gem individually.

### ISSUE THREAD

**Issue by avellable** [bundler/bundler-features#102]
Currently bundler doesn't support specifying 'target installing directory' in Gemfile for each gem individually. This issue is a request to support this behavior.

e.g.

```ruby
gem 'slim', target:'/vendor/engines'
```

"target installing directory" : The directory where the gem will be installed.

**Comment by radar** [comment]
What is the benefit of doing this? Why would you want that?

**Comment by avellable** [comment]
Basically, me and my team sometimes felt need to manage(especially installation) engines in rails app using bundler instead of doing it manually. 

Abovementioned is a special case, but if this feature is supported by bundler we can do what we are doing with gem groups to individual gems with only "bundle install".

**Comment by radar** [comment]
I still don't understand.

What we do in an application is this:

```ruby
gem 'catalogue', path: 'engines/catalogue'
gem 'commerce', path: 'engines/commerce'
```

The engines then exist at those paths.

You could also use Bundler's local paths feature: http://ryanbigg.com/2013/08/bundler-local-paths/.

**Comment by avellable** [comment]
Thank you for the link. 
But, to make clear why I suggested this feature: the requirement is to let bundler fetch only specified gems from remote and install them in vendor/engines.

**Comment by segiddins** [comment]
But why would you want to do that for each gem individually? Why isn't the `--path` option sufficient?

**Comment by avellable** [comment]
After thinking and considering current features I don't think this feature is needed. Hence, closing.
