### ISSUE TITLE
Gemfile.local would be really, really, really, useful... Please?

### ISSUE THREAD

**Issue by patrick99e99** [bundler/bundler-features#104]
I've seen a lot of stackoverflow discussion about developers wanting this, and according to this thread

http://stackoverflow.com/questions/4244182/how-to-customize-gemfile-per-developer

It was stated that this was a proposed feature but it was decided to not be included as part of bundler.

...

My situation, I simply want to customize my console by using a tool such as "irbtools". I can't do this (as far as I understand) without adding it to my project's gemfile, and this will result in everyone on my team suddenly having the exact same changes to their console, which is not acceptable. I've also read a lot of people say things like "add a line of code at the end of your Gemfile that will read in a local file, and then you'll get your local gemfile!"--- Except they fail to realize this will result in changes to the Gemfile.lock which is unacceptable.

It is a huge frustration to me that I cannot do this, and as a response I got in the irc forum when talking about this was: "seems like a bad idea, Might lead to 'works on my machine'. "

To which I replied: "the point is, developers should have the freedom to do what they want. if its dangerous for them, then that's their problem. Bundler shouldn't be trying to save developers from themselves".

So, if I can get blessings here, I will gladly make a pr to do the work to enable this feature. But I do not want to waste my time (as I have many times in the past on various "open source projects") trying to make something that is useful to me and others, yet the maintainer says "DENIED" because it goes against whatever-- their "philosophy".

Thank you.

**Comment by indirect** [comment]
That's a pretty hostile "feature request". 😕

The point of Bundler, as a tool, is to guarantee that every developer and server is loading the exact same set of gems. If you don't want to guarantee the exact same set of gems (and it sounds like you don't), Bundler is probably not the tool for you. RubyGems allows loading any gems you want, without forcing every machine to have the same set.

**Comment by indirect** [comment]
Related: Bundler now has support for optional groups. Maybe you can use those to get what you want.

**Comment by indirect** [comment]
One last option: use existing features to provide a Gemfile that isn't in git and only exists for those who want it: https://github.com/rubygems/rubygems.org/pull/1177

**Comment by nateberkopec** [comment]
[Another, slightly different approach.](https://github.com/manageiq/manageiq/blob/c0aa211f645c4b88d377d77d2028d4dedd43719f/Gemfile#L154-L160) I prefer the one in my linked PR because it doesn't mess w/the main Gemfile.

**Comment by patrick99e99** [comment]
@indirect 

I apologize, it was not my intention to be come off as hostile regarding this.  Thank you for the solutions you offered, however they do not seem to work.  When using bundler, 1.11.2, if I do 
bundle config --local gemfile Gemfile.dev", and create a Gemfile.dev, after I run bundle install, it installs all the gems in Gemfile + Gemfile.dev, but when I do "bundle exec rails c", I get:

    Welcome to RAILS. You are using ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]. Have fun ;)
    /Users/patrick/.rvm/gems/ruby-2.2.3@myapp/gems/railties-4.1.4/lib/rails/application.rb:427:in `block in railties_initializers': undefined method `initializers' for #<Instance:0x007fe9583557c0 @delegate=:all> (NoMethodError)

And if I switch Bundler back to use Gemfile instead of Gemfile.dev, then rails c works fine.

I also tried doing rvm gemset empty prior to running bundle with Gemfile.dev configured as my gemfile.   Made no difference.

**Comment by nateberkopec** [comment]
@patrick99e99 I think you'll need to provide some more details or ways to replicate, it works perfectly for me on the rubygems.org app.

**Comment by patrick99e99** [comment]
*  rails new foo
*  cd foo
*  rvm gemset create foo
*  rvm gemset use foo
*  bundle config --local gemfile Gemfile.dev
*  bundle
*  bundle exec rails c

    Welcome to RAILS. You are using ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin12.5.0]. Have fun ;)
    /Users/pcollins3/.rvm/gems/ruby-2.0.0-p451@foo/gems/railties-4.1.4/lib/rails/application.rb:427:in `block in railties_initializers': undefined method `initializers' for #<Instance:0x00000101839800 @delegate=:all> (NoMethodError)  

My Gemfile.dev:
    eval_gemfile(File.expand_path("Gemfile", __dir__))
    gem "irbtools"

**Comment by nateberkopec** [comment]
Thanks. I don't use RVM, but trying that with a fresh Ruby install (2.2.4 but using your Rails version of 4.1.4) worked fine for me, however I can't require 'irbtools' in the rails console either (?). 

What's your .irbrc?

**Comment by patrick99e99** [comment]
aaagh..  sorry..  I just realized, I forgot that irbtools needs:

    gem 'irbtools', require: 'irbtools/binding'

Then it works.  Thanks!

**Comment by patrick99e99** [comment]
The only thing that's a bit of a bummer with this approach is that if I don't do:

    cp Gemfile.lock Gemfile.dev.lock

prior to bundling, then I will not get any of the Gemfile.lock versioning...  Is there anyway around this other than to alias bundle to "cp Gemfile.lock Gemfile.dev.lock && bundle" ?

**Comment by nateberkopec** [comment]
> then I will not get any of the Gemfile.lock versioning

Ah, because it's a separate lockfile. That makes sense. I think you're right - you'd need to copy it over if that mattered to you. @indirect maybe there's a better way to handle that? another feature of Bundler we can bring to bear here? ;)
