### ISSUE TITLE
Option to annotate the gemfile

### ISSUE THREAD

**Issue by jakeonrails** [bundler/bundler-features#109]
Hi,

I think it would be useful to have a way to annotate a Gemfile with comments describing the gems included in the Gemfile, taken from the short description field in a gem's gemspec.

I am happy to write the code to make this happen but I know nothing about the bundler codebase, and seeing as it is quite large, could really use a pointer toward the place in the code that would make the most sense to implement this.

**Comment by segiddins** [comment]
This sounds more like a plugin than core bundler functionality to me, to be honest.

**Comment by jakeonrails** [comment]
Is there some documentation somewhere for how to build a plugin? I can't find anything on the bundler homepage and it's not searchable (AFAIK)

Also, for a tool such as this, I would think it would need access to the metadata bundler retrieves when it fetches stuff from rubygems. Having this thing run as a plugin would mean having to make a whole separate series of requests to rubygems, right? Or does the plugin system have a hook that I could tap into to fetch this data?

**Comment by segiddins** [comment]
You can name an executable `bundle-foo` and you're always free to `require 'bundler'` ;)

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4538
