### ISSUE TITLE
Feature: gem count of both "Required" and "Bundled"

### ISSUE THREAD

**Issue by danielpclark** [bundler/bundler-features#110]
Like the command line option `bundle list` I think it would be nice to get the count of gems printed out.

For example this bash script does it nicely.

    printf "Required gems: $(cat Gemfile | grep gem -c)\nBundled gems: $(bundle list | wc -l)\n"
    Required gems: 95 
    Bundled gems: 239

**Comment by indirect** [comment]
IIRC, both of these numbers are printed in the output of `bundle install`.

**Comment by RochesterinNYC** [comment]
I think @indirect is referring to the following in the output of `bundle install`:

```
...
Installing rails 4.2.5.1
Installing sass-rails 4.0.5
Installing rails_admin 0.8.1
Bundle complete! 4 Gemfile dependencies, 61 gems now installed.
```

**Comment by danielpclark** [comment]
I see.  If one were to add metrics on Gem counts in their testing and reporting it would be nice to have a fast and efficient result on this.

    time printf "Required gems: $(cat Gemfile | grep gem -c)\nBundled gems: $(bundle list | wc -l)\n"

    real      0m0.755s
    user      0m0.686s
    sys       0m0.074s


    time bundle install

    real      0m2.549s
    user      0m2.372s
    sys       0m0.175s

I suspect having code written for this feature would be even faster than using `wc -l` (to read the line output of gems) and bundle install will only get slower the more gems are in the Gemfile.

**Comment by indirect** [comment]
Maybe `bundle show --count`? @segiddins, do you have opinions?

**Comment by segiddins** [comment]
Whispers softly *plugins*

**Comment by RochesterinNYC** [comment]
So we don't want to make this a flag?

Something like:
```
$ bundle show --count
Specified gems: 3
Bundled gems: 54
```

**Comment by indirect** [comment]
@RochesterinNYC how about a `bundle-count` gem that provides the `bundle-count` command that prints those two lines, and then you can `gem install bundle-count && bundle count`? That seems to satisfy both the requester and @segiddins 😆

**Comment by RochesterinNYC** [comment]
Sorry, accidentally pushed to my fork's master instead of a side branch and it seems to have auto-closed this (didn't know that behavior with fork master branches could happen).

Opened a PR (bundler/bundler#4293) with the implementation of `bundle show --count`. I'm okay with it being merged or closed as something we decide we don't want in the CLI.

**Comment by indirect** [comment]
@RochesterinNYC 😆 perfect. if you're interested in making the gem, go for it. If not, maybe @danielpclark would be willing to create the `bundle-count` gem? Bundler will automatically delegate the `bundle count` command to the `bundle-count` script, if you have one installed.
