### ISSUE TITLE
Notify of major version updates on `bundle update`

### ISSUE THREAD

**Issue by tejasbubane** [bundler/bundler-features#113]
Moving the discussion from https://github.com/bundler/bundler/issues/4313 over here.

Currently `bundler` silently updates the gems even if it is a major update. 
eg.

```
⇒  bundle update
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using diff-lcs 1.2.5
Installing rspec-support 3.4.1
Using bundler 1.11.2
Installing rspec-core 3.4.3 (was 2.14.8)
Installing rspec-expectations 3.4.0 (was 2.14.5)
Installing rspec-mocks 3.4.1 (was 2.14.6)
Installing rspec 3.4.0 (was 2.14.0)
Bundle updated!
⇒  bundler -v
Bundler version 1.11.2
```

This might happen when you update old applications with no version numbers specified in `Gemfile`.
eg.

```
gem 'rspec'
```

I think it would be nice to notify users how many gems were updated in total and how many of them were major version upgrades (like `rspec` and its dependencies in the above example).
If possible we should also ask users to look at the changelog for those major releases since they can have breaking changes.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4515
