### ISSUE TITLE
Bundler resolve on ruby version

### ISSUE THREAD

**Issue by schneems** [bundler/bundler-features#115]
Recently I ran into a problem while running tests on travis for rails_stdout_logging. The tests use various versions of Rails which use mail which uses mime-types. Recently mime-types 3 included a dependency on https://rubygems.org/gems/mime-types-data which is Ruby 2+ only. When bundler resolved the `bundle update` on travis it picked the latest version of mime-types even when being run on Ruby 1.9 versions.

Here's the issue thread https://github.com/heroku/rails_stdout_logging/pull/25#issuecomment-200423071

Here's the travis log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/118007848/log.txt

The error:

```
[32mInstalling mime-types-data 3.2016.0221[0m

[33mGem::InstallError: mime-types-data requires Ruby version >= 2.0.[0m
[32mInstalling xpath 2.0.0[0m
[32mInstalling railties 4.0.13[0m
[32mInstalling sprockets-rails 2.3.3[0m
[32mInstalling activerecord 4.0.13[0m
[31mAn error occurred while installing mime-types-data (3.2016.0221), and Bundler
cannot continue.
Make sure that `gem install mime-types-data -v '3.2016.0221'` succeeds before
bundling.[0m

[31;1mThe command "eval bundle install --jobs=3 --retry=3" failed 3 times.[0m

```

If bundler took into account the Ruby version restrictions it could have been possible to see that mime-types 3 couldn't be installed on the system but a lower dependency could have version 2.6.2.

I'm curious if there has been any talk about incorporating Ruby version restrictions in bundler's gem restrictions. How difficult would something like that be? Has anyone tried before?

BTW I posted this to the mailing list last month but it doesn't look like anyone is actively moderating the list

**Comment by segiddins** [comment]
@schneems this is already included in 1.12, as long as you've specified your ruby version in your Gemfile and you're pulling from a source that serves the new bundler index.

**Comment by schneems** [comment]
🚀

**Comment by schneems** [comment]
I just grok-d the changelog again and don't see that called out. Am I missing it, or is that something we can add in?

**Comment by segiddins** [comment]
It was a resolver feature in 1.11, but only the new index has the necessary metadata.

**Comment by schneems** [comment]
Okay, i see it now

> when gempec required_ruby_version is available and the Gemfile specifies a ruby version, resolve for the given ruby version (@segiddins)

Thanks for the feature! What does a gem have to do to make sure they're compliant moving forwards if anything?

**Comment by segiddins** [comment]
Gems dont have to do anything.
