### ISSUE TITLE
Remove sticky command line options "feature"

### ISSUE THREAD

**Issue by dlovellrw** [bundler/bundler-features#116]
Just found in our documentation:

Install the required gems, making sure that you don't get burned by Bundler's unfortunate feature that saves certain command-line options from previous invocations.
```
rm .bundler/config
bundle
```

Can't say how often I've been burned by this.  Would the community accept a pull request that removes this "feature?"  Yeah, sorry.  I haven't looked to see how many times this has already been discussed.  But if it keeps coming up...

**Comment by TimMoore** [comment]
We don't want to change the behavior in the Bundler 1.x series, since it would be a backwards-incompatible change, but I believe it has already been changed on the 2.x branch.
