### ISSUE TITLE
Option to specify directory on `bundle gem`

### ISSUE THREAD

**Issue by zeiv** [bundler/bundler-features#117]
I use GitHub a lot.  Usually I will create my repo online so GitHub can generate my README and LICENSE and generally make life easier, then clone it onto my machine and start developing.  When I'm creating a new gem however, Bundler also makes it own directory.  Often, what I want to name my gem is _not_ the same as what I want to name my repository.  So, here is what I propose:

- A flag such as `bundle gem my-gem-name --dir my-existing-gem-repo` to specify that Bundler should generate the gem in that directory.

- **And/Or** a flag to simply have the gem generated in the current directory: `bundle gem my-gem --current-dir`

Thoughts?

**Comment by segiddins** [comment]
I think this is straying out of `bundle gem` territory and more towards standalone tools like `ore`

**Comment by zeiv** [comment]
I agree that Bundler should not focus on gem bootstrapping, however I don't think the option to specify a directory is a huge step outside the minimal functionality that Bundler does provide.  Especially when you consider the other gem boilerplate functionality that Bundler _does_ provide, such as `--bin` and `--ext`.  Adding this option would only involve a small amount of code, as well.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4537
