### ISSUE TITLE
after/before installation hook

### ISSUE THREAD

**Issue by lxsameer** [bundler/bundler-features#118]
Hi, I added a small feature to `Bundler` which allows users to run a code block before/after bundle install action.  For example:

```ruby
after_install do
   # do something you like
end
```

This feature have lots of usages for example i used this to create my TAGS file and run specific test cases.

**Comment by RochesterinNYC** [comment]
What are some specific/explicit use cases for this functionality? You mention a TAGS file and running specific test cases but I'm not sure what you exactly mean by these.

Additionally, how does this functionality accomplish or perform operations that you couldn't just do before or after running `bundle install` in whatever script or shell being used?

If you have `pre-hook-action.sh` and `post-hook-action.sh` that contain the actions you want to run respectively before and after bundle install, why should these be run in a `Gemfile` via:

```ruby
before_install 'pre-hook-action.sh'
after_install 'post-hook-action.sh'
```

rather than the following in a script or shell:

```bash
pre-hook-action.sh
bundle install
post-hook-action.sh
```
?

**Comment by lxsameer** [comment]
This solution is more rubyish. For example ( my current use case ) I need to create an special format of ctags with each bundle install. I iterate over all the gems on my `Gemfile` and generate a ctag from their source then collect all these ctags in a TAGS file. Then My IDE use this TAGS file to navigate and autocomplete my code. Using this solution I can work as always with out worrying about updating my `TAGS` file every time I change my gem list. I can do the same using `guard` or similar stuff but that is too much, I can't expect my users ( IDE users ) to install guard and its plugin for such functionality.

Another use case would be to run some test cases. For example I have several test cases with tests some critical parts of my project and I want to make sure that installing/updating my gem list won't break any thing. I can do it via normal testing solutions but using this one bundler can do the work for me even if i forget to do it.

**Comment by indirect** [comment]
@lxsameer this gem already automatically generates ctags for gems as they are installed by Bundler, using the RubyGems install hooks that Bundler already supports: https://github.com/tpope/gem-ctags. Do you have any other use-cases for this kind of hook?

**Comment by lxsameer** [comment]
I already used that gem. For a normal ctag that may be the answer bug not in general. 

Any ways. As an end user I really want to have easy to use and learn solutions ( I think most users are like me ) so i thought this may be a good idea. But judging by the number of rejected PRs and feature  discussions with the same idea in mind, I guess that `Bundler` code team do not like this and want to implement their own version. So I think it's better for me to wait and see what you guys will do with it. I hope it turns out to be awesome.
