### ISSUE TITLE
Allow a minimum ruby version in Gemfile

### ISSUE THREAD

**Issue by moore3071** [bundler/bundler-features#119]
Allow for setting a minimum ruby version at least to the minor version number in the gemfile. This would be very helpful when working with a cross-distro group that doesn't want to use rvm (an Arch user with a Debian user pulling from pacman's repos and dpkg for their respective Ruby packages).

**Comment by segiddins** [comment]
As of 1.12, you can do `ruby "~> 2.3.0"`, does that accomplish what you need?

**Comment by moore3071** [comment]
That does, I've just seen little documentation of it, and a general search reveals some [weirder solutions](http://stackoverflow.com/questions/28440712/how-can-i-specify-a-minimum-ruby-version-in-a-gemfile). Thanks for you help.
