### ISSUE TITLE
if current Ruby isn't support by latest gem version, fall back to earlier + warn user

### ISSUE THREAD

**Issue by e2** [bundler/bundler-features#120]
I haven't investigated if this can be done (or even if it should be).

(NOTE: not related to Ruby version in Gemfile. This is about a Ruby version dependency inside a gem's gemspec).

### Actual: 

Installation fails if a gem depends on a newer version of Ruby.

### Expected (nice to have):

 Bundler could resolve the gem to an earlier version that is still supported on given Ruby version.

### Example:

`Gemfile`:

```ruby
source 'https://rubygems.org'
gem 'guard'
```

```
$ bundle update
(...)
Installing listen 3.1.1
Gem::InstallError: listen requires Ruby version ~> 2.2.
An error occurred while installing listen (3.1.1), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.1'` succeeds before bundling.
```

I think it would be fair to Bundler to install Listen v3.0.8.

NOTE: SemVer doesn't specify whether bumping the dependency on Ruby by a minor requires a major bump in the gem. 

Although obviously RubyGems cannot install Ruby to satisfy dependencies - I see no reason why it shouldn't pick a version of a gem that can work.

Reasoning: at some point a bug in a given Ruby version may create a need to bump a dependency on another API-compatible Ruby. This is actually a "bugfix" (so the bump is at patch-level).

I believe Ruby should be treated just like any other gem - with the except that it can't be installed or upgraded.

Would a PR for this make sense for Bundler < 2 ?

**Comment by indirect** [comment]
We just gained the ability to do this with the new index. You can try it by running `gem install bundler --pre`, and then adding a `ruby "2.0"` line to your Gemfile. We're still hashing out exactly how to support version requirements when the Gemfile does not contain a ruby version.

**Comment by e2** [comment]
AWESOME! IT WORKS BEAUTIFULLY!

:heart_eyes: :heart_eyes: :heart_eyes:

**Comment by e2** [comment]
> We're still hashing out exactly how to support version requirements when the Gemfile does not contain a ruby version.

I don't have a Ruby version requirement in the Gemfile. I have one in a gem.

I considered a workaround where people can just include a special gem that has a strict requirement on a given Ruby. E.g. a gem called, let's say, "ruby-lock-version", where version 2.3 of the gem locks to Ruby 2.3 in the gemspec.

The only "weird" thing is: I'm using Bundler for a non-Rails app - just to resolve dependencies that RubyGems can't.

Anyway, I'm blown away by how nicely this works (it picks an earlier version of a gem!).

It made my day!
