### ISSUE TITLE
Allow ruby version requirement strings

### ISSUE THREAD

**Issue by sodabrew** [bundler/bundler-features#13]
This would be useful:

```ruby
ruby '~> 1.9.3'
```

Previously: https://github.com/bundler/bundler/issues/2213
PR submitted at: https://github.com/bundler/bundler/issues/2228

**Comment by donv** [comment]
:+1:  for this.  A very important feature.  And yes, the lock file must contain the locked version just as with the gem versions.

**Comment by indirect** [comment]
If it's so important to you, maybe you should sent a pull request!

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4555
