### ISSUE TITLE
Provide a recommended way to use developer specific gems

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#16]
For instance, I want to use `pry` and `guard` but don't want to force it on my team. We should either

* Document that this is explicitly not recommended with bundler, with rationale.
* Document the recommended way to do this with current features.
* Provide a feature that enables this.

From https://github.com/bundler/bundler/issues/2190.

Note that a solution needs to be able to nicely handle conflicts between developer gems and team gems.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4518
