### ISSUE TITLE
Support dry runs for operations.

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#2]
From https://github.com/bundler/bundler/issues/2575

Current best way to figure out what will change is to run `bundle update` and then `git diff Gemfile.lock`. That's not terrible, but a `--dry-run` flag could make sense if it didn't add much complexity.

A few other suggestions from @sheerun:

Or add few flags to gem outdates:
* `--update | --gemfile` - shows which gems would be affected by `bundle update`
* `--patch` - shows only patch updates for gems specified in Gemfile.lock
* `--minor` - shows only minor updates for gems specified in Gemfile.lock

`--minor` and `--patch` could be useful for example on following situation:

Among others I defined `gem 'rails', '~> 3.1.0` in my Gemfile, and usually I just run `bundle outdated --gemfile` to know if I should update patch version of Rails. But from time to time I'd like to know it there is minor (not major) update for rails, so I run `bundle outdated --minor` and it shows me `rails 3.2.13` is out (not `4.0.0`).

In my dreams there would be `bundle outdated --security` flag too ;)

**Comment by rud** [comment]
`bundle outdated --strict` honors your `Gemfile` constraints and shows you what new versions match. Does that make this issue closable?

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4516
