### ISSUE TITLE
Add simple 'read_gemfile' API

### ISSUE THREAD

**Issue by bitops** [bundler/bundler-features#25]
It would be quite convenient if Bundler exposed a simple API like Bundler.read_gemfile(path_to_gemfile) which took the path to a Gemfile, analyzed its dependencies, and returned a list of Gem specifications, similar to Bundler.setup. This API should just work without having to mess with environments or any such thing.

**Comment by segiddins** [comment]
This is already what a `Bundler::Definition` does under the hood...

**Comment by bitops** [comment]
Then you won't mind exposing an easy way to get to it? :)

**Comment by segiddins** [comment]
Right now, none of that API is public (because it's undocumented and considered an implementation detail of bundler), but you can already get what you need via

```ruby
require 'bundler'
definition = Bundler::Definition.build(path_to_gemfile, path_to_lockfile, whether_to_unlock_locked_specs)
specs = definition.specs
```

**Comment by bitops** [comment]
Cool, thanks for the heads-up. 

Fwiw my original use case for this some time back was doing open source license compliance checking. An API that makes it easy to suck in the Gemfile and start traversing all the known gems and their directories is a *super* helpful API to have available. 

In particular, it's helpful when gem authors don't have license information specified in their gem file. At that point, navigating to the installed gem directory via Bundler is really awesome for doing license file scanning. 

Anyway, thanks for getting back to me! :)
