### ISSUE TITLE
Stop remembering options passed to `install`

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-features#26]
In Bundler 2.0, flags passed to commands will no longer be remembered, and instead should be set using `bundle config` if they should apply to every run. Running `bundle install --without production` _might_ still need to be remembered, but I would like to try out not remembering it first.

**Comment by asymmetric** [comment]
@indirect is there any documentation as to the reasoning behind this change? What's the drawback with the current system, and what's the benefit in changing?

**Comment by indirect** [comment]
https://trello.com/c/yGsPNDpg

**Comment by asymmetric** [comment]
@indirect you were saying in bundler/bundler#2812 only options that apply at install time should be allowed in `install.

IMHO that means removing `--system` and `deployment` too, since they change the install path.

Do you agree?

**Comment by indirect** [comment]
Yes, --system will be removed. The --deployment flag is special, and changing the path is only part of what it does. The deployment flag will continue to install in frozen mode, but will no longer change the path.

**Comment by asymmetric** [comment]
I see. Given that gems [won't be installed to the system path anymore](https://trello.com/c/K4zdOFl8/51-default-installs-to-path-bundle-gems), and that `--system` will be removed from `install`, how will users install gems to the system path? Will they have to specify that path explicitly to `bundle config path`?

**Comment by fotanus** [comment]
Can we close this?

**Comment by indirect** [comment]
yes, it is done in the 2-0-dev branch
