### ISSUE TITLE
Keep track of checksum per gem

### ISSUE THREAD

**Issue by Bertg** [bundler/bundler-features#27]
More and more people are getting worried about the safety of gems and the ecosystem around it. There are some nice project on their way (signed gems etc...) but it might still be some time before these are main stream. And that might still not fix issues with git based gems etc.

What I'm suggesting here is not a 100% fail safe system. What I'd like to do here is add to Bundler's "The gems you run locally will be the gems on your server" guarantee. 

I'm suggesting to add a checksum to the Gemfile.lock file per gem. When creating the lockfile we create a checksum per gem and store it in the file.
On install, specifically when retrieving a gem from a foreign source, we again make the checksum and compare. 
This should add a significant amount of confidence that the source of the gem isn't compromised and that I'm running the exact same version on all machines. 

What do you think?

**Comment by marnen** [comment]
What is the current status of this feature? The current NPM/Kik/Azer kerfuffle points (if indirectly) to how badly this is needed.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4550
