### ISSUE TITLE
Respect dependencies while installing in parallel

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-features#29]
The current parallel installation option (`install -jN`) doesn't check to make sure that the dependencies of the gem that is being installed have already been installed. In some edge cases this might cause gem installation to fail (if gem needs to be compiled and depends on the compiled results of one of its dependencies, for example).

If the parallel installer only installs gems whose dependencies have been installed already, that would clear the way for making it the default installation method in Bundler 2.0.

**Comment by segiddins** [comment]
@indirect this has been done for forever?

**Comment by indirect** [comment]
We should close this then :P
