### ISSUE TITLE
Add an "add" command to add gems to the Gemfile

### ISSUE THREAD

**Issue by ryanstout** [bundler/bundler-features#32]
Similar to https://github.com/DruRly/gemrat and NPM, it would be really useful to be able to say

    bundle add nokogiri

and have the gem added to the end of the Gemfile, then bundled.  With a lot of projects, it seems like a very common workflow to add gems without version numbers.  (I see bundler has inject is included, but it requires a version number.  Also, add seems like a better name)

I can implement this as a pull request, I wanted to discuss it before I went to build it however.  (As suggested in the development guide)

**Comment by RochesterinNYC** [comment]
@indirect @segiddins 

Is this something that we still want to pursue? I'd be interested in (re)implementing it.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4546
