### ISSUE TITLE
Summarize all the 'using gem'

### ISSUE THREAD

**Issue by marcandre** [bundler/bundler-features#33]
When doing bundle, it would be nice to have only a summary of the gems for which no change is happening, e.g. writing at the end "Using 42 already installed gems"

**Comment by nickborromeo** [comment]
@TimMoore @indirect what is that status of this feature? bundler/bundler#2873 was closed because it seems this is already partially implemented on master, and that work seems to be the most relevant work for this.

**Comment by indirect** [comment]
@nickborromeo the breaking changes are not yet made to bundler 2.0, want to send a pull request to the 2-0-dev branch?

**Comment by TimMoore** [comment]
@nickborromeo the status is that in Bundler 1.8 and later, it prints a summary at the end of the install:

```
Bundle complete! 73 Gemfile dependencies, 197 gems now installed.
Bundled gems are installed into ./.bundle.
```

There still is no way to suppress the "Using" messages.

**Comment by nickborromeo** [comment]
@indirect what do you mean by "breaking changes"?
@TimMoore I am not sure what you meant by 
> There still is no way to suppress the "Using" messages.

**Comment by TimMoore** [comment]
@nickborromeo this feature request is to not show the messages listing all of the already-installed gems unless you run `bundle install --verbose`. Nobody has implemented that correctly yet.

@indirect has said that he doesn't want the output to change in the 1.x series, only in 2.0, so this would need to be a pull request against the `2-0-dev` branch.

**Comment by nickborromeo** [comment]
Got it. I will take stab at this and let you guys know if I have any questions. Thanks!

**Comment by nickborromeo** [comment]
@TimMoore I tried tracing the code so I can understand the flow and ended up here 
```ruby
    def install_sequentially(standalone, force = false)
      specs.each do |spec|
        message = install_gem_from_spec spec, standalone, 0, force
        if message
          Installer.post_install_messages[spec.name] = message
        end
      end
    end
```

I however do not know where `specs` comes from and where is it is defined. Can you point me to the right direction?

**Comment by TimMoore** [comment]
@nickborromeo it's inherited from `Environment` in `lib/bundler/environment.rb`, which calls `@definition.specs`, defined in `lib/bundler/definition.rb`. `Definition#specs` is more or less the main method, which resolves all of the gems, but I don't think you'll need to make any changes there.

The code that prints the message is in `Installer#install_gem_from_spec`:

```ruby
      if install_message.include? 'Installing'
        Bundler.ui.confirm install_message
      else
        Bundler.ui.info install_message
      end
```

I _think_ that changing that `Bundler.ui.info` to `Bundler.ui.debug` will do the trick. There's more work involved in changing the tests

Thanks for taking this on!

**Comment by hbd225** [comment]
Hi, does anyone take a look at this?
Hope this feature will be merged so I'm going to send a pull request if there is nobody working on :)

**Comment by segiddins** [comment]
@hbd225 a PR to the `2-0-dev` branch would be awesome!

**Comment by hbd225** [comment]
@segiddins Thanks for replying!
I've created a PR for this: bundler/bundler#3872

**Comment by agis-** [comment]
This was implemented in https://github.com/bundler/bundler/pull/3872.
