### ISSUE TITLE
Bundler.with_clean_env should only reset bundler specific variables

### ISSUE THREAD

**Issue by cedrics** [bundler/bundler-features#34]
`Bundler.with_clean_env` currently resets the environment to the state when `Bundler` was required. This makes setting the `ENV` constant from Ruby ineffective. I think `with_clean_env` should only reset the variables that can actually influence the execution of Bundler.

I am using environment variables to configure a complicated test setup. I was previously using an own implementation of `with_clean_env` that broke when upgrading to a newer bundler version in one specific case.

Would this be a feature you are interested in?

**Comment by brauliobo** [comment]
+1 had to do some ugly workaround to use the initially set variables

**Comment by brauliobo** [comment]
nice, `with_original_env` seems to work! it is not documented at http://bundler.io/v1.10/man/bundle-exec.1.html though

**Comment by brauliobo** [comment]
in the end I had to use `with_clean_env` so I guess it is important too

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4499, please continue discussion there!
