### ISSUE TITLE
Warn on unsupported Ruby/Rubygems versions

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler-features#36]
Sometime, new versions of Ruby or Rubygems require updates to Bundler: http://bundler.io/compatibility.html

Other versions are entirely broken.

We should help users out by warning when an unsupported version of Ruby or Rubygems is detected. We may want to have two levels of warning for unknown versions vs. known-bad ones.

If you have an opinion on how this should work, please comment!

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4500, please continue discussion there!
