### ISSUE TITLE
bundle show --paths --without development test

### ISSUE THREAD

**Issue by nathany** [bundler/bundler-features#39]
`bundle show --paths` is [super useful for searching](http://andre.arko.net/2013/05/10/hack-your-bundle-for-fun-and-profit/):

```
ack "stdout" `bundle show --paths`
```

It would be nice to only search against production gems.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4503, please continue discussion there!
