### ISSUE TITLE
Add option --skip-ruby-directive

### ISSUE THREAD

**Issue by zzak** [bundler/bundler-features#45]
In Gemfile you can [specify a ruby version](http://bundler.io/v1.6/gemfile_ruby.html) for your application to depend on, this is used by Heroku when deploying your application.

However during local development, it's sometimes nice to skip this and test other rubies available on your system.

I would like to propose we add this option to skip the directive where possible, mainly install and exec.

I'm not sure what the name should be, so I picked `--skip-ruby-directive`.. open to suggestions.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4505, please continue discussion there!
