### ISSUE TITLE
S3 source support

### ISSUE THREAD

**Issue by alessandrobanjo** [bundler/bundler-features#46]
Rubygems recently added support for S3 private repos (rubygems/rubygems#856), but when I try to use the S3 protocol in Bundler, I get:
```
.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.6.1/lib/bundler/fetcher.rb:279:in `request': undefined method `request_uri' for #<URI::Generic:0x007ffa62906690>
```
Any hope we can have support for protected S3 sources in Bundler too?

Thanks

**Comment by parkr** [comment]
:+1: 

```ruby
gem "rails", s3: "parkerscoolstuff/rails-4.0.5.parker.gem"
```

Great for companies who don't want to have to endure the overhead of `git clone` on deploy or who don't want to ship access to Git-land for non-devs of the gem.

**Comment by godinezj** [comment]
Hi,
  Did this make it into the master branch? If not, can I see the code somewhere? I'd like to give it a go.

**Comment by indirect** [comment]
Because it never quite worked, we haven’t shipped it. It would be awesome to develop this as a Bundler plugin, though!

**Comment by godinezj** [comment]
can you suggest any links on building Bundler plugins?

**Comment by indirect** [comment]
Right now we are still working on them. If you email me, I will invite you to the Bundler Slack and we can talk about it with the GSoC student who is working on implementing them!

**Comment by marcofognog** [comment]
:+1 I would like to have this, it would save me a few steps on build

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4506, please continue discussion there!
