### ISSUE TITLE
Add allowed_push_host to gem template

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-features#49]
Rubygems now allows you to prevent private gems from being able to be pushed to rubygems.org where everyone can see them:

http://guides.rubygems.org/publishing/#serving-your-own-gems

We should add a line with this setting to the gemspec created by `bundle gem` with a TODO to delete the line or enter the URL of the private gem server the gem will be used with.

**Comment by dilumnavanjana** [comment]
Is this ticket still open for development???

**Comment by indirect** [comment]
This is done, so I'm closing.
