### ISSUE TITLE
`bundle pristine` command to revert bundle to original state

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#5]
from @railsjedi: "While debugging something in a rails project, thanks to the awesomeness of `bundle open` I tend to litter my dependencies with logging and debugger statements so I can trace things. At the end, I run `gem pristine --all` to take care of gems I may have hacked up to do. Would be very awesome if bundler also provided a `pristine` command that would revert the bundle to its original state."

From https://github.com/bundler/bundler/issues/524, wide agreement that this would be useful and shouldn't be too difficult to implement.

**Comment by eliotsykes** [comment]
How about if `bundle pristine` outputted help to the user to consider trying `bundle exec gem pristine`?

**Comment by indirect** [comment]
bundle exec gem pristine does not work on git gems. this is a feature.

**Comment by brunobatista** [comment]
:+1:

**Comment by mgenereu** [comment]
:+1:

**Comment by sheerun** [comment]
@indirect Isn't this already implemented in 1.10 with `bundle install --force`?

**Comment by indirect** [comment]
@sheerun the pristine command just unpacks the .gem file again from the disk, while --force downloads the gem again and then installs it.

@segiddins this actually makes me realize that we might not be deleting existing files before force installing... are we?

**Comment by segiddins** [comment]
@indirect no, we just make the source `#install` the spec again

**Comment by indirect** [comment]
@segiddins that's a bug in force, then. we need to nuke the directory, since it's possible that a malicious gem could install files that don't get overwritten when the non-malicious gem is installed. :/

**Comment by segiddins** [comment]
Make an issue on bundler/bundler for me?

-Samuel E. Giddins

On Jun 3, 2015, at 5:10 PM, André Arko <notifications@github.com> wrote:

@segiddins that's a bug in force, then. we need to nuke the directory, since it's possible that a malicious gem could install files that don't get overwritten when the non-malicious gem is installed. :/

**Comment by tjgillies** [comment]
:+1:

**Comment by segiddins** [comment]
Instead of a bunch of :+1:'s, it would be much appreciated if someone made a PR to bundler implementing the feature :)

**Comment by razorcd** [comment]
+1

**Comment by indirect** [comment]
@razorcd where's that pull request? :P

**Comment by akhramov** [comment]
@indirect

Shouldn't `--force` switch be aware of `--local` switch? If both `--force` and `--local` are set then `bundle install --force --local` should do the "pristine thing" (and already does). 

Just a reminder if you're going to change the `--force` behaviour.

**Comment by indirect** [comment]
@akhramov this change has nothing to do with the `--force` option, they are completely separate things

**Comment by schneems** [comment]
Dropped in to say, I would use this feature if it existed.

**Comment by pareidoliax** [comment]
:+1:

**Comment by segiddins** [comment]
Everyone, please stop adding thumbs up -- either use GitHub's emoji reactions on the original issue, or even better send a pull request to bundler implementing the feature.

**Comment by LynnCo** [comment]
Locked, no more thumbs up to be had here. Also closing in favor of https://github.com/bundler/bundler/issues/4509
