### ISSUE TITLE
refactor Bundler::Index's @specs to Hash of Hashes

### ISSUE THREAD

**Issue by dmcclory** [bundler/bundler-features#50]
Hello Bundler Team!

I ran the default bundler command with a simple Gemfile through RubyProf and poked around the output. I found that the command spent about 70% of it's time iterating over lists of specs and calling `Bundler::Index#same_version?`

As I looked around, I learned that the basic structure of Index is a Hash of Arrays. This adds some extra unnecessary work. Every time a new spec is added, the Index has to check for duplicates in the list. And every time you want to look up a spec, you have to walk down it.

The Index index should use Hashes to store the different versions of a gem; right now it's using an Array as a Hash. Lookup of specific gem versions would be constant. The secondary key could be a combination of version number & platform.

I spent a little time refactoring, and got it working. The external interface for `Bundler::Index` is unchanged.

It was also a bit faster. On a simple Gemfile, it took off about half a second of execution time (user). On a Gemfile for a production app, it took off about 2 seconds.

I'm going to submit a pull request. Could you give it a read and let me know if there are any blockers which would prevent this from being merged in? I'll also submit a separate PR with some Yard docs.

**Comment by segiddins** [comment]
Can be closed as https://github.com/bundler/bundler/pull/3010 was merged.
