### ISSUE TITLE
Graceful handling of transient network failures

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler-features#53]
Bundler should rescue `Bundler::HTTPError` and give a useful error instead of a backtrace.

@indirect said on bundler/bundler#2769:

> We should probably rescue this error and say that we couldn't connect, check your network and status.rubygems.org and try again.

**Comment by envygeeks** [comment]
How many times does bundler retry to fetch because we've been having tons of trouble from Australia with bundler and RubyGems over the last few months, it would be nice if Bundler tried again instead of just throwing us out, this is heavily important to us on our docker instances.

**Comment by indirect** [comment]
@envygeeks it defaults to three times. please open a ticket following [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) if you'd like us to help you troubleshoot.

**Comment by am-kantox** [comment]
@indirect It would be more handy for the end-user whether she could specify `secondary_source` like:

```
source 'https://rubygems.org'
secondary_source 'http://mirror.org'
```

so that the problems with main source would be handled automagically. Currently we are forced to build workarounds with ping-and-rollback-to-other-source.

**Comment by segiddins** [comment]
I believe this is now in bundler, with retrying, mirror fallback, etc ?

**Comment by indirect** [comment]
I think so!
