### ISSUE TITLE
Bug in default gemspec spec.executables

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [bundler/bundler-features#57]
I recently experienced a bug with the default spec.executables in the gemspec generated after "bundle gem new_gem".

I added a folder into a /bin folder, and that caused the command to remove sub-folders in the path of the executables.

    spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }

Example:
If you have a file stored like this:

    bin/sub_binary_folder/some_executable.extension

It will be added as:

    bin/some_executable.extension

And thus the gem won't build.

To fix this, I made the following change:

    spec.executables   = spec.files.grep(%r{^bin/}) { |f| f[3..-1] }

It is a bit crude, but it essentially strips away the extra "bin/" which is prepended to the path.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4544
