### ISSUE TITLE
Better errors when errant space in Gemfile gem name

### ISSUE THREAD

**Issue by benlakey** [bundler/bundler-features#61]
In a Gemfile if you accidentally place a space before/after the gem name within the string like so:

```ruby
gem "minitest ", "~> 5.0"
#            ^ note the space
```

Then the error is as follows, which is technically correct but almost impossible to notice what the problem is at first glance (has an extra space):
    
    $ bundle
    Fetching gem metadata from https://rubygems.org/..
    Resolving dependencies...
    Could not find gem 'minitest  (~> 5.0) ruby' in the gems available on this machine.

I propose one of two possible solutions:

1. Trim leading and trailing whitespace prior to fetching the specified gem.
2. An error message that can hint more clearly that the issue is a leading or trailing space.

The version of Bundler in use for reference:

    $ bundle --version
    Bundler version 1.6.5

**Comment by smlance** [comment]
:+1: 

This can be closed now, right?

**Comment by phiggins** [comment]
@smlance: Looks like it to me. Thanks everyone! :beers:
