### ISSUE TITLE
Make `outdated` output more "grepable"

### ISSUE THREAD

**Issue by eoinkelly** [bundler/bundler-features#63]
`outdated` is great but I think the following would make it even better:

1.  Limit output to only gems mentioned in Gemfile. These are the only ones I can do something about and it is a little frustrating trying to figure out where the Gemfile gems end and the dependencies begin in the current output of `outdated` especially given that most `Gemfile`s are not sorted alphabetically.
2. Filter output by group. I often use `outdated` when about to upgrade an existing rails app and it would be neat to be able to see just the `default` group so I can prioritize upgrading production gems.

A minimal solution for 1 and 2 could be some sort of _verbose_ output that could be run through grep

```
# Gemfile

gem 'devise_invitable', '~> 1.3.3'
gem 'jquery-rails'

group :test, :development do
  gem 'rpsec'
end
```

would generate something like

```
  * devise_invitable (1.3.6 > 1.3.4) Gemfile specifies "~> 1.3.3" in group "default"
  * jquery-rails (3.1.2 > 3.1.0) Gemfile specifies "" in group "default'
  * rspec (3.1.0 > 2.99.0) Gemfile specifies "~> 2.99.0" in groups "test", "development"
```

then I could grep for `Gemfile specifies` to get all gems mentioned in Gemfile and grep for `test` if I want just that group.

**Comment by lime** [comment]
I would love this! `outdated` is invaluable when selectively updating gems, and this would make that process easier.

**Comment by indirect** [comment]
This sounds great.

**Comment by segiddins** [comment]
Closed via https://github.com/bundler/bundler/pull/3521.
