### ISSUE TITLE
Warn if the ruby version found on the path doesn't match the one Bundler was run with

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler-features#66]
A lot of people run into problems because they have installed Bundler under the system Ruby and not whatever one they have selected with rvm/rbenv/chruby/whatever.

Because gems installed under the system Ruby usually have executables on the default PATH, this often results in Bundler being run with a version of Ruby that is not what the user expects, causing it to install gems in the wrong place, complain about a mis-matched version, etc.

We could make `bundle install` warn about a version mismatch. Good idea or bad idea?

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4542
