### ISSUE TITLE
--newer-only option for install/update

### ISSUE THREAD

**Issue by lime** [bundler/bundler-features#73]
Or `--no-downgrade`, `--update-only`, etc. Suggestions welcome.

Basically a flag that would make Bundler not even consider versions that are older than those currently used.

#### Why?

Accidental downgrading is a problem that baffles you the first time you encounter it (e.g. https://github.com/bundler/bundler/issues/2474, https://github.com/bundler/bundler/issues/1266). Then you learn to specify a minimum version constraint, to ensure you're not suddenly dropped to version 0.0.2 when two depending gems clash.

However, your actual use case is often the following:
  1. When adding gems, I want the newest versions that are compatible with the rest of my gems.
  2. When updating, I want a newer version if possible, **the current version otherwise**.

To achieve this, I have to be on the lookout for downgrades myself in my `diff`s, or I can bump the minimum version constraints to always match currently installed versions. But that sounds an awful lot like manual work. With `--newer-only` I would know that Bundler will fail rather than downgrading, allowing me to resolve conflicts manually only when they arise.

Another potential benefit (in fact the reason I came up with this idea) is that it limits the search space when resolving dependencies. Which hopefully could give us a speedup...?

#### How?

You could think of it as adding a silent `>=` constraint to each gem installed (even those not specified in the Gemfile). As an example Bundler would essentially interpret this Gemfile:

```ruby
# Gemfile
gem 'faker', '~> 1.4'
gem 'hirb'
```

with the following versions currently installed:
```ruby
# Gemfile.lock
GEM
  specs:
    faker (1.4.3)
      i18n (~> 0.5)
    hirb (0.7.2)
    i18n (0.7.0)
```

as this:
```ruby
# Gemfile
gem 'faker', '~> 1.4', '>= 1.4.3'
gem 'hirb', '>= 0.7.2'
gem 'i18n', '>= 0.7.0'
```

I'm not very familiar with the Bundler codebase, so I can't say if this would be feasible to implement. I there is interest for this feature, however, I'd gladly take a stab at it.

**Comment by indirect** [comment]
I think you're right, and this should be the the way `update` works in Bundler 2.0. In the meantime, I think having a flag to opt in (or an option you can set via `bundle config --global` is a good solution. Thanks for writing this up.
