### ISSUE TITLE
full-index option per source

### ISSUE THREAD

**Issue by tomykaira** [bundler/bundler-features#74]
With recent bundler releases, we must use `--full-index` option to get gems from a private repo generated by `gem generate_index` command.
However, `--full-index` option drastically slows `bundle install`.

I want to specify `full-index` per `source` in `Gemfile`.

image:

```ruby
source 'https://rubygems.org'
source 'https://user:password@private-repo.example.com', full_index: true
```

**Comment by TimMoore** [comment]
> With recent bundler releases, we must use --full-index option to get gems from a private repo generated by gem generate_index command.

That's not the intended behaviour... it should be able to fall back on a full index automatically if a source doesn't support the dependency API. Sounds like you've found a bug.

Could you open a new issue at https://github.com/bundler/bundler/issues/new please?

Include:
* The output from `bundle env` (with any private credentials masked)
* The output from `bundle install --verbose` (again, with credentials masked)

Thanks!

**Comment by tomykaira** [comment]
Thank you. It's good news!
I've opened a bug report as adviced, then close this.
