### ISSUE TITLE
Custom globbing per dependency

### ISSUE THREAD

**Issue by rjnienaber** [bundler/bundler-features#75]
I host private gems on an internal gem server ([Gem in a box](https://github.com/geminabox/geminabox)). For a variety of reasons, this has become sub-optimal for my project, so what I would like to do instead host them in a github repo and pull them from there. All my code lives in a single repo like the following

```
/gems
  /common
    common.gemspec
/internal
  /app_1
    Gemfile --> reference 'common' gem
/external
  /app_2
    Gemfile --> reference 'common' gem
```

With this setup, I would like to reference a gem in the 'gems' folder. However, looking at the documentation, there is no easy way to do this. I didn't find any documentation that said this was possible so I looked over the code and found [this](https://github.com/bundler/bundler/blob/b5589a0d18c3d99457ae45f82f4a11be1e5af553/lib/bundler/source/git.rb#L15):

```ruby
@glob = options["glob"] || DEFAULT_GLOB
```
I thought I could just pass a `:glob` option in my Gemfile but it failed with the following:

```
$ bundle
You passed :glob as an option for gem 'common', but it is invalid. Valid options are: group, groups, git, path, name, branch, ref, tag, require, submodules, platform, platforms, type, source
``` 
Looking further I found that `:glob` is not a currently permitted parameter in [dsl.rb](https://github.com/bundler/bundler/blob/b5589a0d18c3d99457ae45f82f4a11be1e5af553/lib/bundler/dsl.rb#L234).

```ruby
@valid_keys ||= %w(group groups git svn path name branch ref tag require submodules platform platforms type source)
``` 

I edited the source code of bundler to allow the `:glob` parameter and then it worked as I thought it should. Also, I found another issue ([#3286](https://github.com/bundler/bundler/issues/3286)) that could have benefitted from this feature so I wonder if it would be worth making this change?

**Comment by indirect** [comment]
Can't you just do this using :path?

**Comment by rjnienaber** [comment]
I'd still like to be able to specify other options like `:branch`, `:tag` or `:ref`. Sometimes, I run different versions of the same gem with different apps.

**Comment by indirect** [comment]
You can't use `:ref` or any of the related options on a gem that's in the same repository as the Gemfile. Can you give actual example Gemfiles?
