### ISSUE TITLE
gist dependencies

### ISSUE THREAD

**Issue by steakknife** [bundler/bundler-features#78]
### Yuck

```ruby
gem 'contrived', git: 'https://gist.github.com/b80fe32305890c2a8286.git'
```

### Not yuck

```ruby
gem 'contrived', gist: 'b80fe32305890c2a8286'
```

**Comment by indirect** [comment]
You can already do this yourself:

```ruby
# Gemfile

git_source(:gist) do |id|
  "https://gist.github.com/#{id}.git"
end

gem 'contrived', gist: 'b80fe32305890c2a8286'
```

**Comment by steakknife** [comment]
Much thanks.

**Comment by steakknife** [comment]
A stolen microgem for microgems.  

https://gist.github.com/steakknife/a309f56048fac3071dcc

**Comment by steakknife** [comment]
Actually, it's already part of the DSL.  So, it's all good. :)

https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L207

**Comment by TimMoore** [comment]
Yeah it was always intended for end users, but it missed the docs when it was first released. Docs have been updated on master, but haven't bern released yet.

**Comment by steakknife** [comment]
No worries, it's my fault for not combing sources and just trying it. :)
