### ISSUE TITLE
Allow setting the version of ruby via the .ruby-version file

### ISSUE THREAD

**Issue by danielocallaghan** [bundler/bundler-features#79]
In order to allow specifying the apps required ruby version in a single place it might be nice to allow bundler to load the version number dynamically by simply reading in the file:
Currently I have this working locally with something like this in my Gemfile
```ruby
def set_ruby_from_version_file(filename='.ruby-version')
  ruby File.read(filename).match(/(\d+\.\d+\.\d+)/).to_s
end

set_ruby_from_version_file
```
```
$ cat .ruby-version
2.2.0
```
so would just be a matter of adding a new method to the bundler api to facilitate this.

**Comment by leondewey** [comment]
:+1:

**Comment by simi** [comment]
I think this can be closed since it was rejected in https://github.com/bundler/bundler/issues/3441.

**Comment by danielocallaghan** [comment]
this isn't quite the same thing as https://github.com/bundler/bundler/pull/3441
its still an opt in behaviour which shouldn't break anything, just makes things more declarative/clearer.

**Comment by segiddins** [comment]
You can always do `ruby File.read('.ruby-version).strip`

**Comment by danielocallaghan** [comment]
some .ruby-version files seem to have a 'ruby-' prefix: 
```
$ cat .ruby-version
ruby-2.1.4
```

not sure why, not a big deal either way
