### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#8]
Allow people to write plugins that supply commands like `bundle foo`, and provide hooks to respond to events such as `after_install`.

This has been discussed quite a lot already. For context, please see:

* @indirect's original ticket description https://github.com/bundler/bundler/issues/1945 and his blog post http://andre.arko.net/2012/07/23/towards-a-bundler-plugin-system/
* Heroku's plugin system: https://github.com/heroku/heroku/blob/master/lib/heroku/command/plugins.rb
* @mitchellh description and evaluation of vagrant's plugin system: https://github.com/bundler/bundler/issues/1945#issuecomment-7192407
* Vagrant plugin documentation: http://docs.vagrantup.com/v2/plugins/development-basics.html

# Use Cases

* Profiling

From @BMoreaty:

"If there were a plugin system today, I would write a `bundle profile` plugin that tells me which gems in my bundle take the longest to load. To do this I would need these hooks:

`before_require` - passes in the name of the file that is about to be required. I suppose it wouldn't hurt to also pass in the dependency object.
`after_require` - passes the file name and dependency again. Also passes the `LoadError` instance that was raised, if any."

* License command that shows license information for all gems.
* Generate documentation with `ri` for installed gems.

From https://github.com/bundler/bundler/issues/1945

**Comment by rykov** [comment]
As an additional use case, we at @gemfury would love to be able to write a plugin that loads private credentials (into ENV maybe) before `bundle install` so that our customers don't have to store them in clear text in their Gemfiles.

**Comment by TimMoore** [comment]
Hi @rykov that feature already exists! :smile:

http://bundler.io/v1.7/man/gemfile.5.html#CREDENTIALS-credentials-

**Comment by rykov** [comment]
Ah, nice! :+1: But, we would still like to be able to inject credentials from our config or from `~/.netrc` without having the customer go through `bundle config` flow.

**Comment by indirect** [comment]
Bundler reads credentials from ENV today.

**Comment by rykov** [comment]
Thanks for settings me straight on the latest - it's been a while.  And big thanks to @TimMoore for reaching out and helping me updated the docs.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/3463
