### ISSUE TITLE
Including full ruby interpreter path with binstubs shebang

### ISSUE THREAD

**Issue by alanfranz** [bundler/bundler-features#84]
Hello,
I'm proposing a feature for which I'm willing to contribute the implementation as well, if you think it would be possible to accept it in upstream bundler.

My issue is: I don't want to be forced to use a ruby version manager (be it rvm, rbenv or whatever it may be) that forces me to load something as a function in my shell in order to use a certain ruby version. I've had some nightmares with such approach especially with CI servers and native full-fledged packages to be built for some distros. 

So: I just like to have "clean" ruby interpreters (standard lib + rubygems + bundler and nothing else) for different versions in standard and predictable paths, and use bundler for project-specific libraries. Those can be installed with a ruby version manager or even by hand (typically I've got an isolated package in /opt/something for production servers)

Then, I'd like to do something like
```
/opt/ruby-2.1.5/bin/bundle --binstubs --path=mybundle
```
In my project directory and have my bundler installed.

**This already works**. But the generated binstubs have ```/usr/bin/env ruby``` as their shebang, thus requiring something else to set the proper ruby to be used at runtime.

From my tests so far, simply setting the full ruby interpreter path as the shebang in the generated binstubs does the trick.

I'm sure there may be a) edge cases where something does not work properly and b) that sometimes it might not work at all because of how some version managers handle rubies, so I think that such feature should be enabled by an option (--binstubs-fullpath), and yet it would be very useful in order to create standalone, isolated executables that require absolutely no external interaction to work.

Python virtualenv works in a similar fashion: whenever creating a virtualenv (which actually creates a copy of the python interpreter, but that's a nonrelevant detail here) a "bin" subdirectory is created with some default executable scripts (e.g. pip, python's own package manager) which have a shebang that points to the just copied python executable. So, such scripts are executed **within** the virtualenv's context even when the virtualenv has not been sourced, and nothing else being virtualenv-aware is installed in the system.

Let me know what you think.

**Comment by indirect** [comment]
I recommend creating a shell alias for `bundle binstubs --shebang=$(which ruby)` if you want full paths. Because binstubs are usually checked in to a project repo, the common case will always be to use the first Ruby on the path.

**Comment by alanfranz** [comment]
It seems that I had just missed the shebang option. I don't usually commit binstubs, I just include a Makefile/Rakefile to recreate them.

By the way, bundler already does what I need. Thank you.
