### ISSUE TITLE
Adding the ability to specify a subpath inside a git repository.

### ISSUE THREAD

**Issue by nicolasnoble** [bundler/bundler-features#87]
This is to cater for a very small set of repositories around

In the case you have a project that is written in C for example, but wants to provide bindings for various languages, it would be nice to have a way to support this.

An example would be this project: https://github.com/grpc/grpc - its `src` directory contains the bindings for various kind of languages, all of them around the core library, written in C.

Having everything in one repository drastically simplifies the workflow and the cohesion of the project. Sadly, this prevents us from having a gem that can work from git.

I wrote a small change to bundler as a way to express what I'd love to have: nicolasnoble/bundler@413cb88022a5df3a5f943a483546a279340502b1

With that simple change, I can do for example:

```
gem 'grpc', :git => 'https://github.com/grpc/grpc.git', :subpath => 'src/ruby'
```

And I'll get my dependency installed properly.

Another way I was thinking of would be to have some sort of mechanism where from the root directory there'd be a `.gemdir` file that contains the subpath to actually use, but I wasn't really sure about how to achieve that properly.

What do you think ?

**Comment by segiddins** [comment]
This shouldn't be necessary, as `git` gems will have their directory searched recursively for gemspecs.

**Comment by nicolasnoble** [comment]
Really ? That's not the behavior I am seeing at the moment. Right now, doing this:

```
gem 'grpc', :git => 'https://github.com/grpc/grpc.git'
```

fails, even though there is a gemspec here: https://github.com/grpc/grpc/blob/master/src/ruby/grpc.gemspec

How is this supposed to work ? Is there something missing ?

**Comment by nicolasnoble** [comment]
Also, the documentation right now explicitly mentions that the gemspec needs to be at the root of the git repository: http://bundler.io/git.html

```
Specify that a gem should come from a git repository with a .gemspec at its root
```

Which is why I didn't even search for a recursive system at all.

**Comment by TimMoore** [comment]
It doesn't seem to be documented (contributions would be welcome!) but the pattern that it uses to find the gemspec is customizable with a `glob` option: https://github.com/bundler/bundler/blob/master/lib/bundler/source/git.rb#L15

The default ([inherited from path](https://github.com/bundler/bundler/blob/master/lib/bundler/source/path.rb#L11)) is to only search the first level of subdirectories.

**Comment by TimMoore** [comment]
Sorry, I just realised that this is only available in pre-release versions. You can install with `gem install --pre bundler`.

**Comment by segiddins** [comment]
Just verified that `gem 'grpc', :git => 'https://github.com/grpc/grpc.git', glob: 'src/ruby/*.gemspec'` works in 1.10 pre.

**Comment by nicolasnoble** [comment]
Thanks, wasn't aware of that new option!
