### ISSUE TITLE
Need to be able to push signed tags

### ISSUE THREAD

**Issue by todb-r7** [bundler/bundler-features#90]
Currently, `rake release` pushes a version tag up to github in an unsigned way. Thus, it gets difficult to say with any certainty who pushed a tag on a project with multiple committers.

I couldn't find anything in the documentation about an environment variable or other option where I can specify a signing key for the version tag. Note, I'm not looking specifically for signing a **gem** (with a PEM certificate), I'm just looking to sign a **tag commit**.

All about signing commits: http://mikegerwitz.com/papers/git-horror-story

If I've just missed this in the docs, an RTFM with a pointer would help a ton.

Thanks!

**Comment by indirect** [comment]
Bundler does not support signing commits or releases--if you would like to do so, I suggest overriding the Rake task for releasing.

**Comment by todb-r7** [comment]
> Bundler does not support signing commits or releases--if you would like to do so, I suggest overriding the Rake task for releasing.

Ah good, then this is a proper feature request then, and not merely a noob question.

I'd argue that it's important that Bundler allow people to do the secure thing as simplr config option. Ideally, as a strongly encouraged option.

**Comment by indirect** [comment]
Thanks for the feature request! You're the first person to ever request that Bundler support signing release tags, which is why I suggested that you could overwrite the Rake task to get the functionality you're asking for.

The Bundler gem functionality is deliberately designed to only cover the most common use-cases, and today signing commits is not a common use-case. We'll take this request under consideration for the future, but at present it's unlikely.

**Comment by todb-r7** [comment]
>  signing commits is not a common use-case

I bet if Bundler supported it, it'd become common. :)

**Comment by indirect** [comment]
The Bundler gem functionality has, so far, merely implemented the most common practice for gems, rather than dictating what those practices should be. :)

**Comment by Mange** [comment]
It should be mentioned that creating a signed tag is the "default" for `git`, and that it's mostly Github that has created the current trend of not signing tags.

Would a pull request be welcome, if I did one?

**Comment by rmm5t** [comment]
It might be worth reconsidering this given that GitHub now supports and is promoting signed git tags. 

An idea: If the `user.signingkey` git config variable is present, presume that a signed tags is desired; otherwise, stick with the default behavior of an unsigned tag.

**Comment by LynnCo** [comment]
This issue was moved to bundler/bundler#4540
