### ISSUE TITLE
binstubs support on windows

### ISSUE THREAD

**Issue by elovelan** [bundler/bundler-features#92]
Unless you're running under cygwin, msys or another POSIX compatibility layer, Windows doesn't know how to interpret ``#!/usr/bin/env ruby``.

I would be happy to implement this but want to get some feedback first. I should be able to borrow most of [the code from RubyGems](https://github.com/rubygems/rubygems/blob/40e59d5619ac176cb7c0d76829f817b63fe145e1/lib/rubygems/installer.rb#L436)

**Comment by indirect** [comment]
Sounds good to me!
