### ISSUE TITLE
--skip-dependencies option

### ISSUE THREAD

**Issue by agis-** [bundler/bundler-features#96]
Crossposting from https://github.com/wycats/bundler/issues/143.

**Comment by indirect** [comment]
I believe it's already possible to do this by putting the gems you don't want installed in a `without` group.

**Comment by bolandrm** [comment]
@indirect can you please provide an example?

**Comment by indirect** [comment]
@bolandrm please read the docs about how to use groups and --without.

**Comment by quinn** [comment]
@indirect the goal for me with this would be to prevent a specific gem from having it's dependencies included in the gem resolution because the gem author screwed something up or whatever. does that make sense?

**Comment by indirect** [comment]
@quinn Bundler provides git gems specifically so you can fork the gem and address those kind of issues.
