### ISSUE TITLE
bundle subcommand -h should print help

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-features#97]
It would be nice if all ways to get help worked as expected. Today we support `bundle help install`, but not `bundle install --help` or `bundle install -h`. We should also make sure that `bundle --help install` works while we're at it.

**Comment by segiddins** [comment]
Does Thor not do this by default?

**Comment by indirect** [comment]
Apparently not given the ticket asking for this feature on bundler/bundler.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/pull/4178.
