### ISSUE TITLE
Add option to disable all checks for local git repos

### ISSUE THREAD

**Issue by jonleighton** [bundler/bundler-features#99]
I use the `:git` source in my gemfile to install gems from our private company repos. I like this because we update these gems frequently and using git avoids the friction of having to bump the gem version, build it, push it somewhere, then `bundle update mygem` in the repository which uses `mygem`.

I also have a git checkout of `mygem` locally, and use the `local.mygem` config option to tell bundler to use this local checkout during development. I do this because:

* Otherwise I'd accumulate lots of checkouts of `mygem` in Bundler's cache, which I'd then have to manually remember to clean out from time to time
* I sometimes like to make changes to `mygem` and then see how they interact with my repository which uses `mygem`. Using `local.mygem` prevents me having to edit the `Gemfile` when doing this.

Unfortunately, there is still some friction in this workflow:

* When my local checkout of `mygem` has a later revision than what is in the `Gemfile.lock`, bundler will automatically update the `Gemfile.lock`. This problem is made worse by using [Spring](https://github.com/rails/spring); when I switch branch it is common that Spring will detect that the application needs to be restarted. It will do so, and in the process Bundler will overwrite the `Gemfile.lock`. This means that my working tree is now dirty. If I `git reset --hard` to reset the `Gemfile.lock` change, Spring will detect that change and restart, thus re-implementing the `Gemfile.lock` change. So it doesn't work. In this situation, I need to `spring stop` and then `git reset --hard`; often I do this before merging in another branch which already included the updated `Gemfile.lock` anyway (but I can't do the merge with a dirty working tree).
* When a colleague has updated the `Gemfile.lock` revision and my local checkout doesn't contain that revision, I get the message: "The Gemfile lock is pointing to revision x but the current branch in your local override for mygem does not contain such commit. Please make sure your branch is up to date."

I would basically like to use the `local.mygem` config option to make a gem which would install from a `:git` source in production operate like a `:path` source on my local machine. In other words, I don't care about differences between the git revision in my local checkout vs the `Gemfile.lock`, and I realise that I may burn myself by not having the correct revision in my local checkout, but that's an acceptable compromise for me.

Note that I already use the `disable_local_branch_check` option so that I can create a separate branch to work on during development.

I'd like to propose a new option: `disable_git_checks`. This option would do what `disable_local_branch_check` does, as well as:

* Not caring if the local checkout doesn't contain the required revision
* Not updating Gemfile.lock automatically to reflect the revision in my local checkout

I am willing to be relaxed about these checks in my development environment because I have confidence that my CI server would pick up any crucial incompatibilities.

If this proposal (or a similar suggestion) sounds good, I am willing to work on a PR to implement it.

Thanks for your time.

**Comment by indirect** [comment]
It is unlikely that we will officially support an option like this, because it removes the primary guarantee of using Bundler: the same code on every machine that runs `bundle install`. Since you would like to get rid of that guarantee, I don't think Bundler is a good fit for you here.

It sounds to me like what you want is simply code that adds your checkout to the load path and then requires it, without running a resolver or referring to a lock. Can you get the result that you want by running some code that is local to your machine only and modifies the load path to remove the git repo and add your checked out repo's path?

**Comment by jonleighton** [comment]
Thanks for the feedback.

> It is unlikely that we will officially support an option like this, because it removes the primary guarantee of using Bundler: the same code on every machine that runs bundle install. Since you would like to get rid of that guarantee, I don't think Bundler is a good fit for you here.

I do think that guarantee is already broken by the `:path` option, since Bundler has no way to ensure that two separate machines contain the same files in `:path`. However, I take the general point.

I appreciate the nudge to consider other solutions. I found https://github.com/cristibalan/braid and will probably end up using that.
